openapi: 3.1.0
info:
  title: Trivia API
  description: An API for managing trivia questions, including importing, exporting, and deleting questions.
  version: 1.2.0
servers:
  - url: https://trivia.sjhannah.com
paths:
  /import:
    post:
      operationId: importQuestions
      summary: Import trivia questions.
      description: Uploads trivia questions to the database. Accepts either a raw CSV (`text/csv`) or a JSON array (`application/json`) payload. Default operation is "append."
      parameters:
        - name: mode
          in: query
          description: The import mode to use.
          required: false
          schema:
            type: string
            enum:
              - append
              - replace_all
              - replace_category
            default: append
      requestBody:
        required: true
        content:
          text/csv:
            schema:
              type: string
              description: |
                Raw CSV content containing trivia questions. The first row must include the following headers:
                - `Category` (string): The category of the trivia question.
                - `Difficulty` (string): The difficulty level (`easy`, `medium`, or `hard`).
                - `Question` (string): The trivia question.
                - `Answer` (string): The correct answer to the question.
              example: |
                Category,Difficulty,Question,Answer
                Science,Easy,What planet is known as the Red Planet?,Mars
                History,Medium,Who was the first president of the United States?,George Washington
          application/json:
            schema:
              type: array
              items:
                type: object
                properties:
                  category:
                    type: string
                    description: The category of the trivia question.
                    example: Science
                  difficulty:
                    type: string
                    description: The difficulty level (`easy`, `medium`, or `hard`).
                    example: easy
                  question:
                    type: string
                    description: The trivia question.
                    example: What planet is known as the Red Planet?
                  answer:
                    type: string
                    description: The correct answer to the question.
                    example: Mars
              description: JSON array of trivia questions.
              example:
                - category: Science
                  difficulty: easy
                  question: What planet is known as the Red Planet?
                  answer: Mars
                - category: History
                  difficulty: medium
                  question: Who was the first president of the United States?
                  answer: George Washington
      responses:
        '200':
          description: Questions imported successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: Questions imported successfully.
        '400':
          description: Invalid request, missing or malformed payload.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Invalid content type. Expected 'text/csv' or 'application/json'.
        '403':
          description: Unauthorized access.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized.
      security:
        - bearerAuth: []

  /export:
    get:
      operationId: exportQuestions
      summary: Export trivia questions.
      description: Exports all trivia questions in the database as a CSV file.
      responses:
        '200':
          description: Trivia questions exported successfully.
          content:
            text/csv:
              schema:
                type: string
                format: binary
        '500':
          description: Internal server error.

  /delete/{category}:
    delete:
      operationId: deleteCategory
      summary: Delete all questions in a specific category.
      description: Removes all trivia questions in the specified category from the database.
      parameters:
        - name: category
          in: path
          required: true
          description: The category to delete questions from.
          schema:
            type: string
      responses:
        '200':
          description: Questions deleted successfully.
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: string
                    example: Questions in category 'Science' deleted successfully.
        '403':
          description: Unauthorized access.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Unauthorized.
        '404':
          description: Category not found.
          content:
            application/json:
              schema:
                type: object
                properties:
                  error:
                    type: string
                    example: Category not found.
      security:
        - bearerAuth: []

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
  schemas: {}
